### ISSUE TITLE
Error while attempt to GameAnalytics.init

### ISSUE THREAD

**Issue by Faketa** [GameAnalytics/GA-SDK-AIR#4]
Hi I can't initialize the GameAnalytics ANE. Any attempts to ```GameAnalytics.init``` trigger an error:
```
11-21 12:32:34.205 29944 30342 I GameAnalytics: Info/GameAnalytics: Info logging enabled
11-21 12:32:34.207 29944 29944 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.adobe.fre.FREObject.getAsString()' on a null object reference
11-21 12:32:34.208 29944 29944 W System.err:    at com.gameanalytics.sdk.utils.FREObjectUtils.getString(Unknown Source:0)
11-21 12:32:34.208 29944 29944 W System.err:    at com.gameanalytics.sdk.functions.InitFunction.call(Unknown Source:57)
11-21 12:32:34.208 29944 29944 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
11-21 12:32:34.208 29944 29944 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
11-21 12:32:34.208 29944 29944 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
11-21 12:32:34.208 29944 29944 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
11-21 12:32:34.208 29944 29944 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:792)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2483)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7208)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:816)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:751)
11-21 12:32:34.208 29944 29944 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
11-21 12:32:34.208 29944 29944 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
11-21 12:32:34.208 29944 29944 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-21 12:32:34.208 29944 29944 W System.err:    at android.os.Looper.loop(Looper.java:193)
11-21 12:32:34.208 29944 29944 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6694)
11-21 12:32:34.208 29944 29944 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-21 12:32:34.208 29944 29944 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-21 12:32:34.209 29944 29944 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-21 12:32:34.210 29944 29944 W System.err: com.adobe.fre.FRENoSuchNameException
11-21 12:32:34.210 29944 29944 W System.err:    at com.adobe.fre.FREObject.getProperty(Native Method)
11-21 12:32:34.210 29944 29944 W System.err:    at com.gameanalytics.sdk.functions.InitFunction.call(Unknown Source:123)
11-21 12:32:34.210 29944 29944 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
11-21 12:32:34.210 29944 29944 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
11-21 12:32:34.210 29944 29944 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
11-21 12:32:34.210 29944 29944 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
11-21 12:32:34.210 29944 29944 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:792)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.SurfaceView.updateSurface(SurfaceView.java:682)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2483)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7208)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
11-21 12:32:34.210 29944 29944 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:816)
11-21 12:32:34.211 29944 29944 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:751)
11-21 12:32:34.211 29944 29944 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
11-21 12:32:34.211 29944 29944 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
11-21 12:32:34.211 29944 29944 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-21 12:32:34.211 29944 29944 W System.err:    at android.os.Looper.loop(Looper.java:193)
11-21 12:32:34.211 29944 29944 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6694)
11-21 12:32:34.211 29944 29944 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-21 12:32:34.211 29944 29944 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-21 12:32:34.211 29944 29944 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
below is my init and config code:
```
GameAnalytics.setEnabledInfoLog(true);
            GameAnalytics.setEnabledVerboseLog(true);
    
            GameAnalytics.config
                .setBuildAndroid("0.3.55")
				.setResourceCurrencies(new Vector.<String>("gems"))
                .setResourceItemTypes(new Vector.<String>(ModelLocator.UNIQUE_ITEM_1))
                .setGameKeyAndroid("b8c8c48b793371994299c8f967df9374")
                .setGameSecretAndroid("50df1097eac4ba09ae11f2e4a233f426b83cc27f");
    
            if(GameAnalytics.init())
            {
                // SDK has been initialized now and you can send events now
				trace ('SDK has been initialized now and you can send events now');
            } else {
				trace ('GA not supported');
			}
```

**Comment by the1schwartz** [comment]
Sorry for the inconvenience. That should be fixed now in the latest version (v3.0.1)
